version: "4.0"
services:
  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    expose:
      - 6379
  db:
    image: "mongo"
    restart: always
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
    expose:
      - 27017
  server:
    build: .
    ports:
      - "3001:${PORT}"
    volumes:
      - server-data:/usr/src/app/src/v1/public
    depends_on:
      - redis
    links:
      - redis
  client:
    build: ../client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server
volumes:
  redis-data:
    driver: local
  server-data:
    driver: local
  db-data:
    driver: local
