version: "4.0"
services:
  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
  db:
    image: "mongo"
    restart: always
    volumes:
      - db-data:/data/db
  web:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - web-data:/usr/src/app/src/v1/public
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
volumes:
  redis-data:
    driver: local
  web-data:
    driver: local
  db-data:
    driver: local