version: "4.0"
services:
  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    expose:
      - 6379
  db:
    image: "mongo"
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=peer-press
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=PeerPress123
    volumes:
      - ./data/mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    ports:
      - "27017:27017"
    expose:
      - 27017
  server:
    build: .
    ports:
      - "3001:${PORT}"
    volumes:
      - ./src/v1/public:/usr/src/app/src/v1/public
    depends_on:
      - redis
    links:
      - redis
  # client:
  #   build: ../client
  #   restart: always
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - server
