version: "4.0"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: "mongo"
    restart: always
    volumes:
      - /data/db:/data/db
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
    links:
      - redis
      - db